version: "3.9"
services:
  rust-server:
    build:
      context: ./server
    container_name: rust-server
    ports:
      - "3001:3001"

  react_frontend:
    build:
      context: ./react_frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - rust-server